### ISSUE TITLE
Numbers repeat rapidly when setting temperature

### ISSUE THREAD

**Issue by dprossner** [ballaswag/guppyscreen#87] opened 2024-04-24 20:57 UTC
when entering numbers to set temperatures on the keypad that pops up, there is no delay before numbers start repeating so entering 200 degrees at a reasonable speed results in 2222220000000000000000. I suggest repeating numbers be disabled altogether when inputting temperatures so one press regardless of duration enters one character.

**Comment by MrDix** [comment] 2024-04-25 02:22
Looks like a duplicate of https://github.com/ballaswag/guppyscreen/issues/76

This was a bug in 0.0.22-beta and 0.0.23-beta and should have been fixed in guppyscreen 0.0.24-beta. Are you using the current version?

**Comment by evgarthub** [comment] 2024-04-25 08:53
Also duplicate of #73

**Comment by dprossner** [comment] 2024-04-26 03:51
my mistake. on me for assuming my helper script installed the latest version

**Closed** 2024-04-26 03:51 UTC
